name: fastlocation
description: App para consulta de CEP e Endereços.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  geocoding: ^2.1.1
  map_launcher: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0
